TravelLaboratory/travel-laboratory-was

src/main/java/site/travellaboratory/be/controller/ArticleController.java
src/main/java/site/travellaboratory/be/controller/dto/ArticleRegisterRequest.java
src/main/java/site/travellaboratory/be/controller/dto/ArticleResponse.java
src/main/java/site/travellaboratory/be/domain/article/Article.java
src/main/java/site/travellaboratory/be/domain/article/ArticleRepository.java
src/main/java/site/travellaboratory/be/domain/article/Duration.java
src/main/java/site/travellaboratory/be/service/ArticleService.java

<br/>
- 여행 계획 쓰기
- 나의 여행 계획 목록
- 여행 계획 상세 기능 구현
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

feat: 여행 계획 쓰기, 나의 여행 계획 목록, 여행 계획 상세 기능 구현

---

src/main/java/site/travellaboratory/be/controller/BookmarkController.java
src/main/java/site/travellaboratory/be/controller/dto/BookmarkResponse.java
src/main/java/site/travellaboratory/be/domain/bookmark/Bookmark.java
src/main/java/site/travellaboratory/be/domain/bookmark/BookmarkRepository.java
src/main/java/site/travellaboratory/be/service/BookmarkService.java

- **작업 이유**: 북마크 조회, 저장 기능 필요
- **관련 이슈**:  ❌
<br/>
- 북마크 전체 조회 기능 구현
- 북마크 저장 기능 구현
<br/>
<br/>
<br/>

feat: 북마크 조회, 저장 기능 구현

---

src/main/java/site/travellaboratory/be/config/SwaggerConfig.java

- 자동으로 기본 url로 셋팅되어서 https가 아닌 http로 보내지는 문제 발생 이를 해결하기 위한 코드

chore: [swagger] server url 설정

---

src/main/java/site/travellaboratory/be/config/WebConfig.java
src/main/java/site/travellaboratory/be/controller/auth/UserAuthController.java
src/main/java/site/travellaboratory/be/controller/auth/dto/UsernameRequest.java
src/main/java/site/travellaboratory/be/controller/auth/dto/UsernameResponse.java
src/main/java/site/travellaboratory/be/service/UserAuthService.java

- 회원가입 로직에서는 이미 존재함 (따로 수정 필요 x)
- **작업 이유**: 회원가입 시 이메일 인증이 없는 현 시스템 특성상 이메일 중복 체크 과정이 필요해서 
- **관련 이슈**: ❌
<br/>
-  이메일(username) 중복 체크 기능 구현
<br/>
<br/>
- ㅎㅇㅌ
<br/>

feat: [auth] /auth/username 이메일(username) 중복 체크 기능 구현

---

src/main/java/site/travellaboratory/be/controller/article/dto/ArticleRegisterRequest.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleResponse.java
src/main/java/site/travellaboratory/be/domain/article/Article.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

feat : 기획 변경에 따른 Article 수정

---

src/main/java/site/travellaboratory/be/common/exception/ErrorCodes.java
src/main/java/site/travellaboratory/be/controller/review/ReviewController.java
src/main/java/site/travellaboratory/be/controller/review/dto/ReviewDeleteResponse.java
src/main/java/site/travellaboratory/be/controller/review/dto/ReviewUpdateResponse.java
src/main/java/site/travellaboratory/be/domain/review/Review.java
src/main/java/site/travellaboratory/be/service/ReviewService.java

- **작업 이유**:  
- 후기 삭제 기능 구현
-  xxResponse.from 으로 통일
<br/>
- 후기 삭제 기능 구현
<br/>
<br/>
<br/>

feat: [review] PATCH /api/v1/reviews/{reviewId}/status - 후기 삭제 기능 구현

---

src/main/java/site/travellaboratory/be/common/exception/ErrorCodes.java
src/main/java/site/travellaboratory/be/controller/review/ReviewController.java
src/main/java/site/travellaboratory/be/controller/review/dto/userlikereview/ReviewToggleLikeResponse.java
src/main/java/site/travellaboratory/be/domain/user/entity/User.java
src/main/java/site/travellaboratory/be/domain/userlikereview/UserLikeReview.java
src/main/java/site/travellaboratory/be/domain/userlikereview/UserLikeReviewRepository.java
src/main/java/site/travellaboratory/be/domain/userlikereview/UserLikeReviewStatus.java
src/main/java/site/travellaboratory/be/service/ReviewService.java

- **작업 이유**: 후기 좋아요 기능 구현
<br/>
- 후기 좋아요 기능 구현
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

Feature/userlikereview v1 - 후기 좋아요 기능 구현

---

build.gradle
src/main/java/site/travellaboratory/be/common/exception/ErrorCodes.java
src/main/java/site/travellaboratory/be/config/S3Config.java
src/main/java/site/travellaboratory/be/controller/user/UserController.java
src/main/java/site/travellaboratory/be/controller/user/dto/ProfileImgUpdateRequest.java
src/main/java/site/travellaboratory/be/controller/user/dto/ProfileImgUpdateResponse.java
src/main/java/site/travellaboratory/be/controller/user/dto/UserProfileUpdateRequest.java
src/main/java/site/travellaboratory/be/controller/user/dto/UserProfileUpdateResponse.java
src/main/java/site/travellaboratory/be/domain/user/entity/User.java
src/main/java/site/travellaboratory/be/service/UserService.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

feat : [S3] 업로드 및 프로필 수정 기능 구현

---

src/main/java/site/travellaboratory/be/controller/article/ArticleController.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleSearchRequest.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleSearchResponse.java
src/main/java/site/travellaboratory/be/domain/article/Article.java
src/main/java/site/travellaboratory/be/domain/article/ArticleRepository.java
src/main/java/site/travellaboratory/be/service/ArticleService.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

feat: [ARTICLE] 검색 기능 구현

---

src/main/resources/application.yml

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

chore: 환경변수 설정

---

src/main/java/site/travellaboratory/be/common/exception/ErrorCodes.java
src/main/java/site/travellaboratory/be/controller/review/ReviewController.java
src/main/java/site/travellaboratory/be/controller/review/dto/ReviewReadDetailResponse.java
src/main/java/site/travellaboratory/be/domain/userlikereview/UserLikeReviewRepository.java
src/main/java/site/travellaboratory/be/service/ReviewService.java

- **작업 이유**: 
- 후기 상세 조회(1) - (feat. 후기 내용 + 후기를 쓴 유저 정보) 기능 구현
- **관련 이슈**:  ❌
<br/>
- 후기 상세 조회(1) - (feat. 후기 내용 + 후기를 쓴 유저 정보) 기능 구현
- 수정, 삭제 권한 is_editable
- 나만 보기 구현 (다른 유저의 나만보기 처리된 글은 조회 시 권한 없음 반환)
- 좋아요 체크 유무 is_like
- 좋아요 개수 like_count
<br/>
<br/>
- 수정, 삭제 권한 is_editable
- 나만 보기 구현 (다른 유저의 나만보기 처리된 글은 조회 시 권한 없음 반환)
- 좋아요 체크 유무 is_like
- 좋아요 개수 like_count
<br/>

feat: [review] 후기 상세 조회(1) - (feat. 후기 내용 + 후기를 쓴 유저 정보) 기능 구현

---

.github/workflows/main-deploy.yml
src/main/resources/application-prod.yml
src/main/resources/application.yml

- **작업 이유**: [config] CD - 이미지 저장을 위한 s3 설정 추가

feat: [config] CD - 이미지 저장을 위한 s3 설정 추가

---

src/main/java/site/travellaboratory/be/common/exception/ErrorCodes.java
src/main/java/site/travellaboratory/be/controller/bookmark/BookmarkController.java
src/main/java/site/travellaboratory/be/controller/bookmark/dto/BookmarkSaveResponse.java
src/main/java/site/travellaboratory/be/domain/article/ArticleRepository.java
src/main/java/site/travellaboratory/be/domain/bookmark/Bookmark.java
src/main/java/site/travellaboratory/be/domain/bookmark/BookmarkRepository.java
src/main/java/site/travellaboratory/be/domain/bookmark/BookmarkStatus.java
src/main/java/site/travellaboratory/be/domain/user/UserRepository.java
src/main/java/site/travellaboratory/be/service/ArticleService.java
src/main/java/site/travellaboratory/be/service/BookmarkService.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

refactor: 북마크 관련 기능 및 아티클 리팩토링

---

src/main/java/site/travellaboratory/be/common/exception/ErrorCodes.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleRegisterRequest.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleResponse.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleSearchRequest.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleSearchResponse.java
src/main/java/site/travellaboratory/be/domain/article/Article.java
src/main/java/site/travellaboratory/be/domain/article/TravelCompanion.java
src/main/java/site/travellaboratory/be/domain/article/TravelStyle.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

refactor: Companion 데이터 타입 변경, Companion, Style enum 정의

---

src/main/java/site/travellaboratory/be/controller/article/dto/ArticleResponse.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

refactor: Enum name -> getName

---

src/main/java/site/travellaboratory/be/controller/article/ArticleController.java
src/main/java/site/travellaboratory/be/controller/bookmark/BookmarkController.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

refactor: api 직관적이게 변경

---

src/main/java/site/travellaboratory/be/common/exception/ErrorCodes.java
src/main/java/site/travellaboratory/be/config/TravelCompanionConverter.java
src/main/java/site/travellaboratory/be/config/TravelStyleConverter.java
src/main/java/site/travellaboratory/be/controller/article/ArticleController.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleUpdateRequest.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleUpdateResponse.java
src/main/java/site/travellaboratory/be/domain/article/Article.java
src/main/java/site/travellaboratory/be/domain/article/TravelStyle.java
src/main/java/site/travellaboratory/be/service/ArticleService.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

Feat: 초기 여행 계획 수정 기능

---

src/main/java/site/travellaboratory/be/controller/bookmark/BookmarkController.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

feat : 북마크 on/off PUT -> PATCH

---

src/main/java/site/travellaboratory/be/controller/article/dto/ArticleSearchResponse.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

feat : Enum name -> getName 변경

---

src/main/java/site/travellaboratory/be/domain/article/TravelStyle.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

refactor: [ARTICLE] style null값 가능하게 변경

---

src/main/java/site/travellaboratory/be/common/exception/ErrorCodes.java
src/main/java/site/travellaboratory/be/controller/article/ArticleController.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleRegisterRequest.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleRegisterResponse.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleResponse.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleSearchResponse.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleUpdateRequest.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleUpdateResponse.java
src/main/java/site/travellaboratory/be/controller/bookmark/BookmarkController.java
src/main/java/site/travellaboratory/be/controller/bookmark/dto/BookmarkResponse.java
src/main/java/site/travellaboratory/be/controller/user/dto/UserProfileUpdateRequest.java
src/main/java/site/travellaboratory/be/controller/user/dto/UserProfileUpdateResponse.java
src/main/java/site/travellaboratory/be/domain/article/Article.java
src/main/java/site/travellaboratory/be/domain/article/Location.java
src/main/java/site/travellaboratory/be/domain/article/TravelStyle.java
src/main/java/site/travellaboratory/be/domain/bookmark/Bookmark.java
src/main/java/site/travellaboratory/be/domain/bookmark/BookmarkRepository.java
src/main/java/site/travellaboratory/be/domain/user/entity/User.java
src/main/java/site/travellaboratory/be/service/ArticleService.java
src/main/java/site/travellaboratory/be/service/BookmarkService.java
src/main/java/site/travellaboratory/be/service/UserService.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

refactor: [ARTICLE, BOOKMARK] Location 변경 및 북마크 개수, 북마크 여부 기능 구현

---

src/main/java/site/travellaboratory/be/controller/user/dto/UserProfileResponse.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

refactor: 프로필 수정 username 삭제

---

src/main/java/site/travellaboratory/be/controller/article/ArticleController.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleResponse.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleSearchResponse.java
src/main/java/site/travellaboratory/be/controller/bookmark/BookmarkController.java
src/main/java/site/travellaboratory/be/controller/user/UserController.java
src/main/java/site/travellaboratory/be/domain/article/ArticleRepository.java
src/main/java/site/travellaboratory/be/service/ArticleService.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

refactor: [ARTICLE] 페이지네이션 및 검색 리팩토링

---

src/main/java/site/travellaboratory/be/common/exception/ErrorCodes.java
src/main/java/site/travellaboratory/be/controller/article/ArticleController.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleRegisterRequest.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleRegisterResponse.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleResponse.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleSearchResponse.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleUpdateRequest.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleUpdateResponse.java
src/main/java/site/travellaboratory/be/controller/bookmark/BookmarkController.java
src/main/java/site/travellaboratory/be/controller/bookmark/dto/BookmarkResponse.java
src/main/java/site/travellaboratory/be/controller/user/UserController.java
src/main/java/site/travellaboratory/be/controller/user/dto/UserProfileResponse.java
src/main/java/site/travellaboratory/be/controller/user/dto/UserProfileUpdateRequest.java
src/main/java/site/travellaboratory/be/controller/user/dto/UserProfileUpdateResponse.java
src/main/java/site/travellaboratory/be/domain/article/Article.java
src/main/java/site/travellaboratory/be/domain/article/ArticleRepository.java
src/main/java/site/travellaboratory/be/domain/article/Location.java
src/main/java/site/travellaboratory/be/domain/article/TravelStyle.java
src/main/java/site/travellaboratory/be/domain/bookmark/Bookmark.java
src/main/java/site/travellaboratory/be/domain/bookmark/BookmarkRepository.java
src/main/java/site/travellaboratory/be/domain/user/entity/User.java
src/main/java/site/travellaboratory/be/service/ArticleService.java
src/main/java/site/travellaboratory/be/service/BookmarkService.java
src/main/java/site/travellaboratory/be/service/UserService.java

- 작업 이유: [배포]
- [ARTICLE] Location 변경, 전체 조회 페이지네이션, 검색 변경
- [Profile] 응답 변경
- [BOOKMARK] 북마크 여부 및 북마크 개수 응답 변경
- 등등,,
관련 이슈: ❌
<br/>
- 위 내용 참고
<br/>
<br/>
- 배포
<br/>

[배포] 아티클 Location 변경, 프로필 변경, 아티클 전체 조회 페이지네이션, 검색 쿼리 파라미터로 변경, 프로필 변경 응답 변경, 북마크 여부 및 북마크 개수 추가 등등

---

src/main/java/site/travellaboratory/be/common/exception/ErrorCodes.java
src/main/java/site/travellaboratory/be/common/exceptionhandler/GlobalExceptionHandler.java
src/main/java/site/travellaboratory/be/controller/articleschedule/ArticleScheduleController.java
src/main/java/site/travellaboratory/be/controller/articleschedule/dto/ArticleScheduleDeleteResponse.java
src/main/java/site/travellaboratory/be/controller/articleschedule/dto/ArticleScheduleRequest.java
src/main/java/site/travellaboratory/be/controller/articleschedule/dto/ArticleScheduleUpdateRequest.java
src/main/java/site/travellaboratory/be/controller/articleschedule/dto/ArticleScheduleUpdateResponse.java
src/main/java/site/travellaboratory/be/domain/article/Article.java
src/main/java/site/travellaboratory/be/domain/articleschedule/ArticleSchedule.java
src/main/java/site/travellaboratory/be/domain/articleschedule/ArticleScheduleRepository.java
src/main/java/site/travellaboratory/be/domain/articleschedule/dtype/ScheduleEtc.java
src/main/java/site/travellaboratory/be/domain/articleschedule/dtype/ScheduleGeneral.java
src/main/java/site/travellaboratory/be/domain/articleschedule/dtype/ScheduleTransport.java
src/main/java/site/travellaboratory/be/service/ArticleScheduleService.java

- **작업 이유**: -
-  PUT 일정 리스트 수정 기능 구현
-  POST 일정 리스트 작성 **제거**
-  PATCH 초기 여행 계획 + 일정 리스트 삭제 기능 구현
<br/>
-  PUT 일정 리스트 수정 기능 구현
-  POST 일정 리스트 작성 **제거**
-  PATCH 초기 여행 계획 + 일정 리스트 삭제 기능 구현
<br/>
<br/>

feat: [schedule]/article_schedule_v1 일정 작성 (제거), 일정 수정, 삭제 기능 구현

---

src/main/java/site/travellaboratory/be/controller/articleschedule/dto/ArticleScheduleRequest.java
src/main/java/site/travellaboratory/be/service/ArticleScheduleService.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

modified: [schedule] ArticleScheduleRequest id -> scheduleId 로 수정

---

src/main/java/site/travellaboratory/be/controller/articleschedule/dto/ArticleScheduleRequest.java
src/main/java/site/travellaboratory/be/service/ArticleScheduleService.java
src/main/resources/application.yml

조회 시 schedule_id 로 하기에 일정 수정 시에도 통일

[배포] [schedule] ArticleScheduleRequest id -> scheduleId 로 수정 

---

src/main/java/site/travellaboratory/be/common/exception/ErrorCodes.java
src/main/java/site/travellaboratory/be/controller/articleschedule/ArticleScheduleController.java
src/main/java/site/travellaboratory/be/controller/articleschedule/dto/ArticleScheduleReadPlacesResponse.java
src/main/java/site/travellaboratory/be/controller/articleschedule/dto/PlaceName.java
src/main/java/site/travellaboratory/be/controller/articleschedule/dto/SchedulePlace.java
src/main/java/site/travellaboratory/be/domain/articleschedule/ArticleScheduleRepository.java
src/main/java/site/travellaboratory/be/service/ArticleScheduleService.java

- **작업 이유**: [review] 후기 작성 전 조회 - 여행 일정별 장소 리스트 기능 구현
- **관련 이슈**:  ❌
<br/>
-  [review] 후기 작성 전 조회 - 여행 일정별 장소 리스트 기능 구현]
- 정렬기준 1순위 방문날짜, 2순위 sortOrder
- TRANSPORT의 경우 출발지명, 도착지명 순으로
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

Feature/schedule v2 - 후기 작성 전 조회 - 여행 일정별 장소 리스트 기능 구현

---

src/main/java/site/travellaboratory/be/controller/auth/UserAuthController.java
src/main/java/site/travellaboratory/be/service/UserAuthService.java

[login, reissue] refresh-token을 cookie -> header 전송으로 변경
- 추후 Cookie 전송으로 변경 예정

tmp: [login, reissue] refresh-token을 cookie -> header 전송으로 변경

---

src/main/java/site/travellaboratory/be/controller/bookmark/BookmarkController.java
src/main/java/site/travellaboratory/be/controller/bookmark/dto/BookmarkResponse.java
src/main/java/site/travellaboratory/be/service/BookmarkService.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

refactor: 올바르지 않은 isBookmarked 수정

---

src/main/java/site/travellaboratory/be/controller/article/dto/ArticleResponse.java
src/main/java/site/travellaboratory/be/service/ArticleService.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

refactor: is_Private 추가

---

src/main/java/site/travellaboratory/be/common/exception/ErrorCodes.java
src/main/java/site/travellaboratory/be/controller/articleschedule/ArticleScheduleController.java
src/main/java/site/travellaboratory/be/controller/articleschedule/dto/ArticleScheduleUpdatePrivacyResponse.java
src/main/java/site/travellaboratory/be/domain/article/Article.java
src/main/java/site/travellaboratory/be/service/ArticleScheduleService.java

- **작업 이유**:
- PATCH 초기 여행 계획+ 일정 리스트 공개 여부 수정 (토글) 기능 
- **관련 이슈**: ❌
<br/>
- PATCH 초기 여행 계획+ 일정 리스트 공개 여부 수정 (토글) 기능 
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

feat: [schedule] PATCH 초기 여행 계획+ 일정 리스트 공개 여부 수정 (토글) 기능 구현

---

src/main/java/site/travellaboratory/be/common/exception/ErrorCodes.java
src/main/java/site/travellaboratory/be/controller/review/ReviewController.java
src/main/java/site/travellaboratory/be/controller/review/dto/ProfileReviewLocation.java
src/main/java/site/travellaboratory/be/controller/review/dto/ProfileReviewPaginationResponse.java
src/main/java/site/travellaboratory/be/controller/review/dto/ProfileReviewResponse.java
src/main/java/site/travellaboratory/be/domain/review/ReviewRepository.java
src/main/java/site/travellaboratory/be/service/ReviewService.java

- **작업 이유**:
-  GET 프로필 - 후기 전체 조회 [페이지네이션] 기능 구현
- **관련 이슈**: ❌
<br/>
- 다른 유저의 리뷰를 볼 수 있도록 구현 (단, 다른 유저의 비공개 리뷰는 볼 수 없음)
- 비공개 리뷰는 본인만 조회 가능
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

feat: [profile]  GET 프로필 - 후기 전체 조회 [페이지네이션] 기능 구현

---

src/main/java/site/travellaboratory/be/domain/article/ArticleRepository.java
src/main/java/site/travellaboratory/be/service/ArticleService.java

- 적용 전 이미지 업로드가 되지 않는 문제가 발생
- 이를 해결하기 위해 @Transactional 추가

fix: [article] updateCoverImage @Transactional 적용

---

src/main/java/site/travellaboratory/be/config/WebConfig.java
src/main/java/site/travellaboratory/be/controller/review/ReviewController.java
src/main/java/site/travellaboratory/be/controller/review/dto/ProfileReviewPaginationResponse.java
src/main/java/site/travellaboratory/be/controller/review/dto/home/BannerReviewLocation.java
src/main/java/site/travellaboratory/be/controller/review/dto/home/ReviewBannerListResponse.java
src/main/java/site/travellaboratory/be/controller/review/dto/home/ReviewBannerResponse.java
src/main/java/site/travellaboratory/be/domain/review/ReviewRepository.java
src/main/java/site/travellaboratory/be/service/ReviewService.java
src/main/resources/application.yml

- **작업 이유**: 프로필 후기 리스트 조회 시 N+1 문제 발생 (해결)
- 홈 배너 후기 리스트 기능 구현
- ❌
<br/>
- 홈(배너) 최신 여행 후기 - 조회 리스트 8개 [feat. 비회원, 회원 공통 항상] 기능 구현
- 프로필 - 후기 전체 조회 [페이지네이션] (N+1) 문제 해결
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

[배포] [banner] 홈(배너) 최신 여행 후기 - 조회 리스트 8개 [feat. 비회원, 회원 공통 항상] 기능 구현+ 프로필 - 후기 전체 조회 [페이지네이션] (N+1) 문재 해결

---

src/main/java/site/travellaboratory/be/controller/review/dto/ProfileReviewResponse.java
src/main/java/site/travellaboratory/be/service/ReviewService.java

- **작업 이유**: 
프로필 - 후기 리스트 전체 조회에 후기 제목 추가
- **관련 이슈**:  ❌
<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

modified: [profile] 프로필 - 후기 전체 조회 수정 (feat. title 추가)

---

src/main/java/site/travellaboratory/be/controller/article/ArticleController.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleOneResponse.java
src/main/java/site/travellaboratory/be/service/ArticleService.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

refactor: 아티클 1개 조회 isEditable 추가

---

src/main/java/site/travellaboratory/be/controller/article/ArticleController.java
src/main/java/site/travellaboratory/be/controller/article/dto/ArticleOneResponse.java
src/main/java/site/travellaboratory/be/service/ArticleService.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

[배포] 초기 여행 계획 1개 조회 isEditable 추가

---

src/main/java/site/travellaboratory/be/controller/auth/UserAuthController.java
src/main/java/site/travellaboratory/be/controller/auth/dto/UserInfoResponse.java
src/main/java/site/travellaboratory/be/controller/auth/dto/UserLoginResponse.java
src/main/java/site/travellaboratory/be/controller/oauth/OAuthController.java
src/main/java/site/travellaboratory/be/service/OAuthService.java
src/main/java/site/travellaboratory/be/service/UserAuthService.java

- **작업 이유**: 
로그인 시 유저의 프로필 이미지가 필요해서 수정
- **관련 이슈**: ❌
<br/>
- [auth] 로그인 시 유저 정보 전달하도록 수정 (feat.role, nickname, profileImgUrl) 
- [oauth] 로그인 시 유저 정보 전달하도록 수정 (feat.role, nickname, profileImgUrl) 
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

Feature/login v3 - modified: [auth]&[oauth] 로그인 시 유저 정보 전달하도록 수정 (feat.role, nickname, profileImgUrl) 

---

src/main/java/site/travellaboratory/be/controller/comment/dto/CommentReadPaginationResponse.java
src/main/java/site/travellaboratory/be/service/CommentService.java

- **관련 이슈**: ❌
<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

modified: [comment] 댓글을 작성하는 유저의 프로필 이미지 데이터 추가

---

src/main/java/site/travellaboratory/be/service/ArticleService.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

refactor: 잘못된 id 변경

---

src/main/java/site/travellaboratory/be/service/ArticleService.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

[배포] 기본 검색 결과에서 잘못된 id값 변경

---

src/main/java/site/travellaboratory/be/domain/article/ArticleRepository.java
src/main/java/site/travellaboratory/be/service/ArticleService.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

refactor: 페이지네이션 리팩토링

---

src/main/java/site/travellaboratory/be/domain/article/ArticleRepository.java
src/main/java/site/travellaboratory/be/service/ArticleService.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

[배포] 검색 페이지네이션 last 오류 해결

---

src/main/java/site/travellaboratory/be/application/article/ArticleReaderService.java
src/main/java/site/travellaboratory/be/infrastructure/domains/article/ArticleRepository.java
src/main/java/site/travellaboratory/be/presentation/article/controller/ArticleReaderController.java

<br/>
- 무슨 기능을 구현했다.
<br/>
<br/>
- 이런 걸 신경쓰세요 
<br/>

feat: [ARTICLE] 전체 조회 기능 구현

---

src/main/java/site/travellaboratory/be/article/presentation/controller/ArticleWriterController.java
src/main/java/site/travellaboratory/be/user/application/_auth/UserRegistrationService.java
src/main/java/site/travellaboratory/be/user/domain/_auth/UserAuth.java
src/main/java/site/travellaboratory/be/user/domain/_auth/request/UserJoinRequest.java
src/test/java/site/travellaboratory/be/article/domain/ArticleTest.java
src/test/java/site/travellaboratory/be/user/domain/_auth/UserAuthTest.java

test: [domain] userAuth 도메인(소형) 테스트 작성 + (feat.coverImage -> cover_img로 수정)

---

src/main/java/site/travellaboratory/be/article/domain/_schedule/ScheduleGeneral.java
src/main/java/site/travellaboratory/be/article/domain/_schedule/request/ArticleScheduleRequest.java
src/main/java/site/travellaboratory/be/article/domain/_schedule/request/ScheduleEtcRequest.java
src/main/java/site/travellaboratory/be/article/domain/_schedule/request/ScheduleGeneralRequest.java
src/main/java/site/travellaboratory/be/article/domain/_schedule/request/ScheduleTransportRequest.java
src/main/java/site/travellaboratory/be/comment/domain/request/CommentSaveRequest.java
src/main/java/site/travellaboratory/be/comment/domain/request/CommentUpdateRequest.java
src/main/java/site/travellaboratory/be/review/domain/request/ReviewSaveRequest.java
src/main/java/site/travellaboratory/be/review/domain/request/ReviewUpdateRequest.java
src/main/java/site/travellaboratory/be/user/application/_auth/UserRegistrationService.java
src/main/java/site/travellaboratory/be/user/domain/User.java
src/test/java/site/travellaboratory/be/article/domain/ArticleTest.java
src/test/java/site/travellaboratory/be/article/domain/_schedule/ArticleScheduleTest.java
src/test/java/site/travellaboratory/be/comment/domain/CommentTest.java
src/test/java/site/travellaboratory/be/review/domain/ReviewTest.java
src/test/java/site/travellaboratory/be/user/domain/UserTest.java
src/test/java/site/travellaboratory/be/user/domain/_pw/PwAnswerTest.java

Feature/domain unit test - 도메인 모델 테스트

---

src/main/java/site/travellaboratory/be/comment/presentation/response/writer/CommentUpdateResponse.java
src/main/java/site/travellaboratory/be/review/presentation/response/writer/ReviewUpdateResponse.java

- **작업 이유**: 불필요한 작업이었음 (원래대로)
<br/>
<br/>

fix: 수정 부분 수정된 내용들은 제외하고 id만 보내는 걸로 (원래대로) 수정 (feat.commentId, reviewId)

---

src/main/java/site/travellaboratory/be/common/exception/ErrorCodes.java
src/main/java/site/travellaboratory/be/user/application/_auth/OAuthService.java
src/main/java/site/travellaboratory/be/user/domain/_auth/request/OAuthJoinRequest.java
src/test/java/site/travellaboratory/be/review/presentation/controller/ReviewWriterControllerTest.java
src/test/java/site/travellaboratory/be/test/assertion/Assertions.java

- **작업 이유**: 후기 삭제 controller 테스트 작성
<br/>

review [WebMvcTest] controller test 작성 (후기 삭제) 

---

src/main/java/site/travellaboratory/be/common/exception/ErrorCodes.java
src/main/java/site/travellaboratory/be/user/application/_auth/UserAuthenticationService.java
src/main/java/site/travellaboratory/be/user/infrastructure/jwt/interceptor/AuthorizationInterceptor.java
src/main/java/site/travellaboratory/be/user/infrastructure/jwt/manager/helper/JwtTokenValidator.java
src/main/java/site/travellaboratory/be/user/infrastructure/persistence/repository/UserJpaRepository.java
src/main/java/site/travellaboratory/be/user/presentation/_auth/controller/UserAuthenticationController.java
src/test/java/site/travellaboratory/be/test/assertion/Assertions.java
src/test/java/site/travellaboratory/be/user/application/_auth/UserAuthenticationServiceTest.java
src/test/java/site/travellaboratory/be/user/infrastructure/jwt/manager/JwtTokenManagerTest.java
src/test/java/site/travellaboratory/be/user/infrastructure/jwt/manager/helper/JwtTokenParserTest.java
src/test/java/site/travellaboratory/be/user/infrastructure/jwt/manager/helper/JwtTokenValidatorTest.java
src/test/java/site/travellaboratory/be/user/infrastructure/persistence/repository/UserJpaRepositoryTest.java
src/test/java/site/travellaboratory/be/user/presentation/_auth/controller/UserAuthenticationControllerTest.java

[Test] 로그인 및 토큰 재발행 기능 - 테스트 작성 (컨트롤러 및 레포지토리)

---

src/main/java/site/travellaboratory/be/article/presentation/controller/ArticleLikeController.java
src/main/java/site/travellaboratory/be/article/presentation/controller/ArticleReaderController.java
src/main/java/site/travellaboratory/be/article/presentation/controller/ArticleWriterController.java
src/main/java/site/travellaboratory/be/article/presentation/controller/_schedule/ArticleScheduleReaderController.java
src/main/java/site/travellaboratory/be/article/presentation/controller/_schedule/ArticleScheduleWriterController.java
src/main/java/site/travellaboratory/be/comment/presentation/controller/CommentLikeController.java
src/main/java/site/travellaboratory/be/comment/presentation/controller/CommentReaderController.java
src/main/java/site/travellaboratory/be/comment/presentation/controller/CommentWriterController.java
src/main/java/site/travellaboratory/be/review/presentation/controller/ReviewLikeController.java
src/main/java/site/travellaboratory/be/review/presentation/controller/ReviewReaderController.java
src/main/java/site/travellaboratory/be/review/presentation/controller/ReviewWriterController.java
src/main/java/site/travellaboratory/be/user/presentation/_auth/controller/OAuthController.java
src/main/java/site/travellaboratory/be/user/presentation/_auth/controller/PwInquiryController.java
src/main/java/site/travellaboratory/be/user/presentation/_auth/controller/UserAuthenticationController.java
src/main/java/site/travellaboratory/be/user/presentation/_auth/controller/UserRegistrationController.java
src/main/java/site/travellaboratory/be/user/presentation/_auth/controller/UserUnregistrationController.java
src/main/java/site/travellaboratory/be/user/presentation/_auth/controller/UserVerificationController.java
src/main/java/site/travellaboratory/be/user/presentation/controller/UserProfileReaderController.java
src/main/java/site/travellaboratory/be/user/presentation/controller/UserProfileWriterController.java

modified: 불필요하게 감싼 ResponseEntity 코드 제거

---

.github/workflows/main-deploy.yml
build.gradle
src/main/resources/application-prod.yml
src/main/resources/application.yml

actuator + promethus를 활용한 모니터링 구축 설정

---

src/main/java/site/travellaboratory/be/article/presentation/response/reader/ArticleOneResponse.java
src/main/java/site/travellaboratory/be/article/presentation/response/reader/ArticleTotalResponse.java
src/main/java/site/travellaboratory/be/article/presentation/response/reader/BannerArticlesResponse.java
src/main/java/site/travellaboratory/be/user/application/service/UserProfileWriterService.java

- **작업 이유**: API 데이터명 통일 및 잘못된 유저 닉네임 수정 로직 해결
<br/>
- name -> nickname으로 통일 및 userId 추가
- 유저 닉네임 잘못된 로직 수정
- 
<br/>
<br/>

Feat: API 데이터명 통일 및 잘못된 유저 닉네임 수정 해결
